- name: gold_linux
  hosts: all
  become: true
  become_method: sudo
  vars:
    temp_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
  tasks:
  - name: Kernel
    sysctl: name=kernel.sched_migration_cost_ns value=5000000
 
  - name: Ratio
    sysctl: name=vm.dirty_background_ratio value=1
 
  - name: Swappiness
    sysctl: name=vm.swappiness value=1
 
  - name: Pressure
    sysctl: name=vm.vfs_cache_pressure value=10
 
  - name: Echo never
    shell: echo never > {{ item }}
    with_items:
      - echo never > /sys/kernel/mm/transparent_hugepage/enabled
      - echo never > /sys/kernel/mm/transparent_hugepage/defrag
 
  - name: Create user postgres
    user: name=postgres password={{ temp_password }} update_password=on_create
